org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true
android.useAndroidX=true
kotlin.code.style=official
# при необходимости fallback:
# org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
